import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg','.woff2':'font/woff2','.txt':'text/plain','.mp4':'video/mp4','.webm':'video/webm'};
const server=http.createServer(async(req,res)=>{try{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/preview\//,'');const file=path.resolve(root,'dist',name||'index.html');if(!file.startsWith(path.join(root,'dist')+path.sep))throw Error();const bytes=await fs.readFile(file);res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream','accept-ranges':'bytes'});res.end(bytes);}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--autoplay-policy=no-user-gesture-required']});
const out=path.join(root,'docs/website');await fs.mkdir(out,{recursive:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'dark',permissions:['clipboard-read','clipboard-write']});const errors=[],failed=[];
page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>failed.push({url:r.url(),error:r.failure()?.errorText}));
// Node fetch uses the environment proxy where the browser cannot. No credentials are read or logged.
await page.route(/^https:\/\//,async route=>{try{const req=route.request();const response=await fetch(req.url(),{method:req.method(),headers:{'content-type':'application/json'},body:req.method()==='POST'?req.postData():undefined,signal:AbortSignal.timeout(20000)});await route.fulfill({status:response.status,body:Buffer.from(await response.arrayBuffer()),headers:{'content-type':response.headers.get('content-type')||'application/json','access-control-allow-origin':'*'}});}catch{await route.abort();}});
const results={mode:'Production export; live read-only RPC, no wallet',checks:[],errors,failed};
const url=`http://127.0.0.1:${server.address().port}/preview/index.html`;
const contrast=async(pairs)=>page.evaluate((pairs)=>{const parse=c=>c.match(/[\d.]+/g).slice(0,3).map(Number);const lum=c=>parse(c).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0);return pairs.map(sel=>{const e=document.querySelector(sel),s=getComputedStyle(e);let bg=s.backgroundColor,p=e;while((bg==='rgba(0, 0, 0, 0)'||/rgba\([^)]*, 0?\.\d+\)$/.test(bg))&&p.parentElement){p=p.parentElement;bg=getComputedStyle(p).backgroundColor;}return {selector:sel,foreground:s.color,background:bg,ratio:Number(((Math.max(lum(s.color),lum(bg))+.05)/(Math.min(lum(s.color),lum(bg))+.05)).toFixed(2))};});},pairs);
try{
 await page.goto(url,{waitUntil:'domcontentloaded'});
 await page.getByText(/Mainnet block/).waitFor({timeout:90000});results.checks.push('Live mainnet snapshot rendered');
 await page.evaluate(()=>document.fonts.ready);assert(await page.evaluate(()=>document.fonts.check('16px Archivo')));results.checks.push('Bundled Archivo font loaded');
 const hero=await page.evaluate(()=>{const v=document.querySelector('.hero-media');return {tag:v.tagName,paused:v.paused,muted:v.muted,loop:v.loop,playsInline:v.playsInline,src:v.currentSrc,ready:v.readyState};});
 assert.equal(hero.tag,'VIDEO');assert(hero.muted&&hero.loop&&hero.playsInline,'hero video attributes');await page.waitForFunction(()=>{const v=document.querySelector('.hero-media');return v.readyState>=2&&!v.paused;},null,{timeout:20000});results.hero=hero;results.checks.push('Desktop hero video autoplays muted, looped, inline from a local source');
 await page.getByRole('button',{name:'Pause background'}).click();assert(await page.evaluate(()=>document.querySelector('.hero-media').paused));await page.getByRole('button',{name:'Play background'}).click();results.checks.push('Hero background has a working pause control');
 for(const width of [1440,900,390,320]){await page.setViewportSize({width,height:1000});await page.getByRole('heading',{name:'Parents of ADAM.'}).scrollIntoViewIfNeeded();await page.waitForFunction(()=>Array.from(document.images).every(i=>i.complete&&i.naturalWidth>0));await page.evaluate(()=>scrollTo(0,0));const overflow=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,inner:innerWidth,wide:Array.from(document.querySelectorAll("body *")).filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,8).map(e=>`${e.tagName}.${e.className} ${Math.round(e.getBoundingClientRect().right)}`)}));assert(overflow.scroll<=overflow.inner,`Overflow at ${width}: ${JSON.stringify(overflow)}`);results.checks.push(`No page overflow at ${width}px`);}
 await page.setViewportSize({width:390,height:844});await page.reload({waitUntil:'domcontentloaded'});await page.getByText(/Mainnet block/).waitFor({timeout:90000});assert.equal(await page.evaluate(()=>document.querySelector('.hero-media').tagName),'IMG');results.checks.push('Compact viewport shows the hero poster instead of autoplay video');
 await page.getByRole('button',{name:'Open menu'}).click();await page.locator('#mobile-nav a',{hasText:'Stake'}).click();assert.equal(new URL(page.url()).hash,'#stake');assert.equal(await page.locator('#mobile-nav').evaluate(e=>getComputedStyle(e).display),'none');results.checks.push('Mobile menu opens, navigates by hash and closes');
 await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(800);await page.screenshot({path:path.join(out,'mobile.jpg'),type:'jpeg',quality:70,fullPage:true});
 await page.emulateMedia({reducedMotion:'reduce'});await page.reload({waitUntil:'domcontentloaded'});await page.getByText(/Mainnet block/).waitFor({timeout:90000});assert.equal(await page.evaluate(()=>document.querySelector('.hero-media').tagName),'IMG');assert.equal(await page.locator('[data-reveal]').first().evaluate(e=>getComputedStyle(e).opacity),'1');assert.equal(await page.locator('button').first().evaluate(e=>getComputedStyle(e).transitionProperty.includes('scale')),false);results.checks.push('Reduced motion: poster instead of video, reveals shown immediately, no press scale');
 await page.emulateMedia({reducedMotion:'no-preference'});await page.setViewportSize({width:1440,height:1000});await page.reload({waitUntil:'domcontentloaded'});await page.getByText(/Mainnet block/).waitFor({timeout:90000});
 await page.getByRole('heading',{name:'ADAM on tour.'}).scrollIntoViewIfNeeded();await page.waitForTimeout(700);const card=page.locator('.watch-card').first();await card.locator('.watch-frame').hover();await page.waitForFunction(()=>!document.querySelector('.watch-card video').paused,null,{timeout:20000});assert(await page.evaluate(()=>document.querySelector('.watch-card video').muted));results.checks.push('Watch card plays on hover, muted by default');
 await card.getByRole('button',{name:'Sound off'}).click();assert.equal(await page.evaluate(()=>document.querySelector('.watch-card video').muted),false);await card.getByRole('button',{name:'Sound on'}).click();results.checks.push('Watch card sound toggle switches muted state');
 await page.mouse.move(5,5);await page.waitForFunction(()=>document.querySelector('.watch-card video').paused);await card.getByRole('button',{name:/Play video/}).click();await page.waitForFunction(()=>!document.querySelector('.watch-card video').paused);await card.getByRole('button',{name:/Pause video/}).click();results.checks.push('Watch card keyboard-accessible play/pause button');
 results.watchLinks=await page.locator('.watch-card a[href*="x.com"]').evaluateAll(a=>a.map(x=>x.href));assert.equal(results.watchLinks.length,2);
 await page.screenshot({path:path.join(out,'watch.jpg'),type:'jpeg',quality:70});
 await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(900);await page.screenshot({path:path.join(out,'desktop.jpg'),type:'jpeg',quality:70});
 await page.getByRole('link',{name:'Stats',exact:true}).first().click();await page.waitForTimeout(1500);results.metrics=await page.locator('.metrics .metric strong').allTextContents();assert(results.metrics.every(t=>t&&t!=='—'),'metrics rendered');results.checks.push('Stat cards render counted values after scroll');
 await page.getByRole('link',{name:'NFT claim',exact:true}).first().click();assert.equal(new URL(page.url()).hash,'#claim');results.checks.push('Hash navigation at IPFS-style subpath');
 await page.getByRole('button',{name:'Connect wallet',exact:true}).first().click();await page.getByText(/No injected wallet found/).waitFor();results.checks.push('Missing wallet recovery message');
 await page.getByRole('button',{name:'Dismiss transaction status'}).click();
 await page.locator('body').click({position:{x:5,y:5}});await page.evaluate(()=>scrollTo(0,0));await page.keyboard.press('Tab');await page.keyboard.press('Tab');await page.keyboard.press('Tab');await page.screenshot({path:path.join(out,'keyboard-focus.jpg'),type:'jpeg',quality:70});results.focus=await page.evaluate(()=>({tag:document.activeElement.tagName,text:document.activeElement.textContent,outline:getComputedStyle(document.activeElement).outlineStyle,color:getComputedStyle(document.activeElement).outlineColor}));
 await page.getByRole('button',{name:'Copy ADAM token address'}).first().click();await page.getByRole('button',{name:'Copied'}).first().waitFor();results.checks.push('Footer contract copy feedback');
 results.footerExplorer=await page.locator('.footer-contracts a[href*="etherscan.io/address/"]').count();assert.equal(results.footerExplorer,6);results.checks.push('Footer lists six contract Etherscan links with copy buttons');
 results.contrast=await contrast(['body','.lead','.primary','.accent-panel p','.muted','.site-header nav a','.eyebrow','.tagline','.footer-contracts code','.badge']);
 for(const v of results.contrast)if(!['.tagline'].includes(v.selector))assert(v.ratio>=4.5,`Contrast ${v.selector}: ${v.ratio}`);results.checks.push('Sampled text pairs on solid backgrounds reach 4.5:1 or better; hero text over video is measured against the dark base only');
 try{await page.getByRole('button',{name:'Load cumulative totals'}).click();await page.getByText(/Fee history complete/).waitFor({timeout:150000});results.totals=await page.getByText(/Fee history complete/).textContent();results.checks.push('Complete fee history and all 3,178 NFT claimed mappings loaded');}catch(e){results.totalsError=String(e.message).slice(0,200);}
 assert.equal(errors.length,0);results.checks.push('No uncaught application errors');
 console.log(JSON.stringify(results,null,2));
}finally{await fs.writeFile(path.join(out,'browser-validation.json'),JSON.stringify(results,null,2)+'\n');await browser.close();await new Promise(resolve=>server.close(resolve));}
