import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { addresses, collections, explorer, links, LP_ID, POOL_ID, QUESTION, rewards } from './config';
import { getClient, read, snapshot, walletData, scanNfts, marketData, feeTotal, claimProgress, type Snapshot, type WalletData, type Nft } from './api';
import { abis } from './contracts';
import { useWallet } from './wallet';
import { amountInput, fmt, short, rankWeights, minimumOut, nextUnlock, countdown, mapAttestation, explain } from './logic';
import { Count, HeroVideo, Icon, WatchCard, XLogo, useReveal } from './media';
import { formatUnits, type Address } from 'viem';
function External({href,children,className=''}:{href:string;children:ReactNode;className?:string}) {return <a className={className} href={href} target="_blank" rel="noopener noreferrer">{children}<Icon name="external" size={14}/><span className="sr-only"> (opens in a new tab)</span></a>;}
function Heading({n,title,lead,children}:{n:string;title:string;lead?:ReactNode;children?:ReactNode}){return <div className="section-heading" data-reveal><div><span className="eyebrow">{n}</span><h2>{title}</h2>{lead&&<p className="lead">{lead}</p>}</div>{children}</div>;}
function Metric({label,value,note}:{label:string;value:ReactNode;note?:ReactNode}) {return <div className="metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>;}
function Copy({text,label='Copy address',compact=false}:{text:string;label?:string;compact?:boolean}){const [state,setState]=useState('');return <button type="button" className={compact?'icon-button':'copy'} aria-label={compact?(state||label):undefined} onClick={async()=>{try{await navigator.clipboard.writeText(text);setState('Copied');}catch{setState('Select the text to copy');}setTimeout(()=>setState(''),2500);}}><Icon name={state==='Copied'?'check':'copy'} size={16}/>{!compact&&(state||label)}</button>;}
const dollars=(n?:number)=>n===undefined?'Unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<1?8:0}).format(n);
const num=(v:bigint|undefined,decimals=18)=>v===undefined?undefined:Number(formatUnits(v,decimals));
const contractNames:Record<string,string>={token:'ADAM token',oracle:'AdamSplitOracle',staking:'AdamDistributorV2',claim:'NFTClaim',treasury:'AdamTreasuryV2',hook:'AdamHook'};
export default function App(){
 const [revision,setRevision]=useState(0),refresh=useCallback(()=>setRevision(n=>n+1),[]);const wallet=useWallet(refresh);const accountRef=useRef(wallet.account);accountRef.current=wallet.account;
 const [data,setData]=useState<Snapshot>(),[dataError,setDataError]=useState(''),[loading,setLoading]=useState(true),[market,setMarket]=useState<{usd?:number;liquidity?:number}>(),[marketError,setMarketError]=useState('');
 const [personal,setPersonal]=useState<WalletData>(),[personalError,setPersonalError]=useState('');const [now,setNow]=useState(Math.floor(Date.now()/1000));const [route,setRoute]=useState(location.hash||'#home');const [menu,setMenu]=useState(false);
 useEffect(()=>{const id=setInterval(()=>setNow(Math.floor(Date.now()/1000)),1000);const refreshId=setInterval(refresh,60000);const hash=()=>{setRoute(location.hash||'#home');setMenu(false);};window.addEventListener('hashchange',hash);return()=>{clearInterval(id);clearInterval(refreshId);window.removeEventListener('hashchange',hash);};},[refresh]);
 useEffect(()=>{let active=true;setLoading(true);setDataError('');snapshot().then(v=>{if(active)setData(v);}).catch(e=>{if(active)setDataError(explain(e));}).finally(()=>{if(active)setLoading(false);});marketData().then(v=>{if(active){setMarket(v);setMarketError('');}}).catch(e=>{if(active){setMarket(undefined);setMarketError(explain(e));}});return()=>{active=false;};},[revision]);
 useEffect(()=>{let active=true;setPersonal(undefined);setPersonalError('');if(wallet.account)walletData(wallet.account).then(v=>{if(active)setPersonal(v);}).catch(e=>{if(active)setPersonalError(explain(e));});return()=>{active=false;};},[wallet.account,revision]);
 useReveal(wallet.account);
 const canWrite=!!wallet.account&&wallet.chain===1&&!wallet.busy;
 const [amount,setAmount]=useState(''),[actionError,setActionError]=useState('');
 const [budget,setBudget]=useState(''),[slippage,setSlippage]=useState('1'),[quote,setQuote]=useState<{amount:bigint;out:bigint;min:bigint;expires:number;account:Address}>(),[quoteBusy,setQuoteBusy]=useState(false),[quoteError,setQuoteError]=useState('');
 const quoteRevision=useRef(0);
 useEffect(()=>{quoteRevision.current++;setQuote(undefined);setQuoteError('');},[budget,slippage,wallet.account,revision]);
 async function stake(unstake=false){setActionError('');try{const value=amountInput(amount);if(!personal)throw Error('Refresh wallet balances before continuing.');if(value>(unstake?personal.staked:personal.balance))throw Error('Amount exceeds your available balance.');await wallet.run(unstake?'Unstake ADAM':'Stake ADAM',async(send,account)=>{if(!unstake){const allowance=await read<bigint>('token','allowance',[account,addresses.staking]);if(allowance<value)await send('token','approve',[addresses.staking,value]);}await send('staking',unstake?'unstake':'stake',[value]);});}catch(e){setActionError(explain(e));document.getElementById('stake-amount')?.focus();}}
 async function getQuote(){const generation=++quoteRevision.current;setQuoteBusy(true);setQuoteError('');setQuote(undefined);try{if(!wallet.account||!personal||!data)throw Error('Connect your wallet and refresh balances first.');const value=amountInput(budget);if(value>personal.budget||value>data.maxClaim)throw Error('Amount exceeds your ETH reward budget or the per-claim limit.');const expires=now+60;const q=await (await getClient()).simulateContract({account:wallet.account,address:addresses.staking,abi:abis.staking,functionName:'claimIMDSTR',args:[value,1n,BigInt(now+600)]});const out=q.result as bigint;const min=minimumOut(out,slippage);if(generation===quoteRevision.current)setQuote({amount:value,out,min,expires,account:wallet.account});}catch(e){if(generation===quoteRevision.current)setQuoteError(explain(e));}finally{setQuoteBusy(false);}}
 const [nfts,setNfts]=useState<Nft[]>(),[scanBusy,setScanBusy]=useState(false),[scanned,setScanned]=useState(0),[scanError,setScanError]=useState(''),[selected,setSelected]=useState<string[]>([]);const scanAbort=useRef<AbortController | undefined>(undefined);
 useEffect(()=>{scanAbort.current?.abort();setNfts(undefined);setSelected([]);setScanBusy(false);setScanned(0);setScanError('');},[wallet.account]);
 async function scan(){if(!wallet.account||wallet.account!==accountRef.current)return;scanAbort.current?.abort();const abort=new AbortController();scanAbort.current=abort;setScanBusy(true);setNfts(undefined);setScanError('');setScanned(0);try{const results=await scanNfts(wallet.account,n=>{if(!abort.signal.aborted)setScanned(n);},abort.signal);if(!abort.signal.aborted&&wallet.account===accountRef.current){setNfts(results);setSelected(results.filter(n=>n.claimable>0n).map(n=>`${n.collection}:${n.id}`));}}catch(e){if(!abort.signal.aborted)setScanError(explain(e));}finally{if(!abort.signal.aborted)setScanBusy(false);}}
 async function claimNfts(stakeClaim:boolean){const chosen=(nfts??[]).filter(n=>n.claimable>0n&&selected.includes(`${n.collection}:${n.id}`));await wallet.run(stakeClaim?'Claim & Stake NFTs':'Claim NFTs',async send=>{for(const collection of collections){const ids=chosen.filter(n=>n.collection===collection.id).map(n=>BigInt(n.id));for(let i=0;i<ids.length;i+=40)await send('claim',stakeClaim?'claimAndStake':'claim',[collection.id,ids.slice(i,i+40)]);}});void scan();}
 const [fees,setFees]=useState<bigint>(),[claimedTotal,setClaimedTotal]=useState<{total:bigint;block:bigint}>(),[totalsBusy,setTotalsBusy]=useState(false),[totalsStatus,setTotalsStatus]=useState('');
 async function totals(){if(!data||totalsBusy)return;setTotalsBusy(true);setTotalsStatus('Reading complete mainnet totals…');try{const [f,c]=await Promise.all([feeTotal(data.block,n=>setTotalsStatus(`Reading fee events: ${n}`)),claimProgress(n=>setTotalsStatus(`Reading claimed allocations: ${n} / 3,178`))]);setFees(f);setClaimedTotal(c);setTotalsStatus(`Fee history complete through block ${data.block}. Claims through block ${c.block}.`);}catch(e){setTotalsStatus(explain(e));}finally{setTotalsBusy(false);}}
 const locked=personal?personal.unlock>now:true;const selectedDue=(nfts??[]).filter(n=>selected.includes(`${n.collection}:${n.id}`)).reduce((n,v)=>n+v.claimable,0n);
 const navItems=[['#about','About'],['#stats','Stats'],['#watch','Watch'],['#claim','NFT claim'],['#stake','Stake']];
 return <>
 <a className="skip" href="#main">Skip to content</a>
 <header className="site-header"><div className="header-inner"><a className="brand" href="#home" aria-label="ADAM home"><img src="./images/adam.jpg" alt="" width="36" height="36"/><span>ADAM</span></a>
  <nav aria-label="Main navigation" className={menu?'is-open':''}>{navItems.map(([href,label])=><a key={href} href={href} aria-current={route===href?'location':undefined}>{label}</a>)}</nav>
  <div className="header-actions"><button type="button" className="wallet-button" onClick={wallet.connect} disabled={wallet.busy}><Icon name="wallet" size={16}/><span>{wallet.account?short(wallet.account):'Connect wallet'}</span></button><button type="button" className="icon-button menu-button" aria-expanded={menu} aria-controls="mobile-nav" aria-label={menu?'Close menu':'Open menu'} onClick={()=>setMenu(m=>!m)}><Icon name={menu?'close':'menu'} size={20}/></button></div></div>
  <div id="mobile-nav" className={`mobile-nav ${menu?'is-open':''}`}>{navItems.map(([href,label])=><a key={href} href={href} onClick={()=>setMenu(false)}>{label}</a>)}</div>
 </header>
 <main id="main">
 <section id="home" className="hero"><div className="hero-bg"><HeroVideo/><div className="hero-shade" aria-hidden="true"/></div>
  <div className="hero-inner"><h1>ADAM</h1><span className="eyebrow hero-eyebrow" data-reveal><span className="status-dot"/>Ethereum mainnet · Uniswap v4 hooked pool</span><p className="tagline" data-reveal>Stake $ADAM. Earn the pool’s fees in IMD, PNKSTR and IMDSTR.</p>
  <div className="actions hero-actions" data-reveal><a className="button primary large" href="#stake"><Icon name="bolt" size={18}/>Stake</a><a className="button glass large" href={links.buy} target="_blank" rel="noopener noreferrer">Buy<Icon name="external" size={16}/><span className="sr-only"> on Uniswap (opens in a new tab)</span></a></div>
  <div className="ca" data-reveal><span className="ca-label">Contract</span><code>{addresses.token}</code><Copy text={addresses.token} compact/><External href={explorer(addresses.token)} className="icon-link">Etherscan</External></div>
  <p className="trade-note" data-reveal>Trade in the official hooked ETH / ADAM pool. Uniswap’s link may select a different route; check the pool before trading.</p></div>
 </section>
 <div className="ticker" aria-label="ADAM highlights"><span>1 billion ADAM</span><b aria-hidden="true">✦</b><span>LP burned forever</span><b aria-hidden="true">✦</b><span>Three reward tokens</span><b aria-hidden="true">✦</b><span>1.5% hook fee to stakers</span></div>
 <section id="stats" className="section"><Heading n="01 · Live stats" title="Onchain. Out in the open." lead={data?`Mainnet block ${data.block.toLocaleString()} · ${new Date(data.time*1000).toUTCString()}`:'Connecting to public Ethereum RPCs…'}><button type="button" onClick={refresh} disabled={loading}><Icon name="refresh" size={16}/>{loading?'Refreshing…':'Refresh stats'}</button></Heading>
  {dataError&&<p role="alert" className="alert">Last refresh failed. Displayed values may be stale. {dataError}</p>}
  <div className="metrics" data-reveal><Metric label="ADAM price" value={<Count value={market?.usd} render={dollars}/>} note={data?`${data.priceEth.toPrecision(5)} ETH · pool spot price`:'ETH price pending'}/><Metric label="Market cap · fixed supply" value={<Count value={market?.usd===undefined?undefined:market.usd*1e9} render={dollars}/>} note="USD price × 1B ADAM"/><Metric label="Pool liquidity" value={<Count value={market?.liquidity} render={dollars}/>} note="USD · DexScreener estimate"/><Metric label="ADAM staked" value={<Count value={num(data?.staked)} render={n=>n.toLocaleString('en-US',{maximumFractionDigits:0})}/>} note={data?`Current hook fee ${data.fee/100}%`:'Reading live contract state'}/></div>
  {marketError&&<p className="muted">USD market data: {marketError} ETH price remains independently sourced from the onchain pool.</p>}
  <div className="stats-detail"><article className="panel accent-panel" data-reveal><div className="card-top"><span className="eyebrow">Today’s oracle split</span><span className="badge">{data?data.split[3]===1?'Signed report':'Equal fallback':'Loading'}</span></div><h3>Buy what’s down.</h3><div className="split-values">{rewards.map((t,i)=><div key={t.key}><strong>{data?`${data.split[0][i]/100}%`:'—'}</strong><span>${t.symbol}</span></div>)}</div><div className="split-bar" aria-hidden="true">{(data?.split[0]??[3333,3333,3334]).map((w,i)=><span key={i} style={{flex:w}}/>)}</div><p>{data?.split[3]===1?`Rank code ${Number(BigInt(data.split[2]))} · order: IMD / PNKSTR / IMDSTR`:data?'No fresh signed report: rewards use equal thirds (rounding to 10,000 bps).':'Waiting for the live oracle response.'}</p>{data?.split[3]===1&&<details><summary>Report ID</summary><code>{data.split[1]}</code></details>}</article>
  <article className="panel" data-reveal><span className="eyebrow">Rewards distributed</span><h3>Paid to stakers so far.</h3><div className="reward-totals">{rewards.map((t,i)=><div key={t.key}><span>${t.symbol}</span><strong><Count value={num(data?.distributed[i],data?.decimals[i]??18)} render={n=>n.toLocaleString('en-US',{maximumFractionDigits:4})}/></strong></div>)}<div><span>IMDSTR ETH budget</span><strong><Count value={num(data?.budgetDistributed)} render={n=>`${n.toLocaleString('en-US',{maximumFractionDigits:4})} ETH`}/></strong></div></div><p className="muted">Cumulative distributor accounting. ETH budgets are bought into IMDSTR on claim; token totals and ETH budgets are separate.</p></article></div>
  <div className="proof-grid"><article className="panel" data-reveal><span className="eyebrow">Liquidity proof</span><h3>{data?data.owner.toLowerCase()===addresses.dead.toLowerCase()?'LP burned. Forever.':'LP owner needs attention':'Checking LP ownership…'}</h3><p>Original LP NFT #{LP_ID.toString()}<br/><code>{data?.owner??addresses.dead}</code></p><External href={links.lp}>Inspect the LP NFT</External><p className="muted">{data?'Owner read from PositionManager on mainnet.':'Expected burn address from launch; live verification pending.'}</p></article>
  <article className="panel" data-reveal><span className="eyebrow">Treasury & NFT progress</span><h3>{fmt(fees)} ETH <small>fees received</small></h3><p>Hook FeeTaken events since deployment. {claimedTotal?`${fmt(claimedTotal.total,18,0)} / 110,000,000 ADAM claimed (${(Number(claimedTotal.total)/1e18/110e6*100).toFixed(2)}%).`:'Load the full NFT claim totals below.'}</p><button type="button" onClick={totals} disabled={!data||totalsBusy}>{totalsBusy?'Loading complete totals…':'Load cumulative totals'}</button><p className="muted" role="status">{totalsStatus}</p></article></div></section>
 <section id="about" className="section"><Heading n="02 · About" title="Made for the whole crew." lead="ADAM connects a playful community to the IMD swarm. Holders who stake share in the rewards generated by trading in the hooked pool."/>
  <div className="allocation" data-reveal><div className="panel"><strong>89%</strong><h3>Into the ocean</h3><p>Single-sided ADAM liquidity. The LP NFT was sent to the dead address, locking the original position forever.</p></div><div className="panel"><strong>11%</strong><h3>Back to the crew</h3><p>10% for IMD NFT holders and 1% for Swarm Pepe. Each NFT’s share unlocks 10% daily for 10 days, starting at launch.</p></div></div>
  <div className="rule-grid">{[['01','Trade fuels rewards','1.5% on every hooked-pool buy and sell. The anti-snipe fee falls from 20% to 1.5% in the first 30 minutes. The owner can only lower the final fee.'],['02','The crew gets 90%','After the 0.5% keeper bounty, fees split 90% to stakers and 10% to the team. Stakers earn IMD, PNKSTR and IMDSTR.'],['03','Buy what’s down','The IMD swarm oracle ranks daily price changes: 50% / 30% / 20%, with the most going to the biggest faller. No fresh report? Equal thirds.'],['04','Stay for the tide','Every new stake locks your entire staked balance for 24 hours. Reward claims remain open. Anyone can process fees for a 0.5% bounty.']].map(([n,t,p])=><div className="rule" key={n} data-reveal><span>{n}</span><h3>{t}</h3><p>{p}</p></div>)}</div>
  <details className="contracts" data-reveal><summary>All mainnet contracts <span>Verified on Etherscan</span></summary><div className="table-wrap"><table><caption>Ethereum mainnet · chain ID 1</caption><thead><tr><th>Contract / role</th><th>Address</th></tr></thead><tbody>{Object.entries(addresses).filter(([n])=>n in contractNames).map(([n,a])=><tr key={n}><th scope="row">{contractNames[n]}</th><td><External href={explorer(a)}><code>{a}</code></External></td></tr>)}</tbody></table></div><p className="pool-key">Official PoolKey: ETH / ADAM · fee 0 · tick spacing 60 · AdamHook.<br/>Pool ID: <code>{POOL_ID}</code></p></details></section>
 <section id="watch" className="section watch-section"><Heading n="03 · Watch" title="ADAM on tour." lead="Straight from the official X account. Hover or tap to play; sound stays off until you turn it on."/>
  <div className="watch-grid"><WatchCard name="rise" title="RISE" text="ADAM takes the stage." href="https://x.com/IaMaDamIMD/status/2107469324206170244"/><WatchCard name="staked" title="Staked and paid" text="Staked $300 of $ADAM and got about $100 in IMDSTR, IMD and PNKSTR in 12 hours." href="https://x.com/IaMaDamIMD/status/2107360470965670193"/></div></section>
 <section id="claim" className="section"><Heading n="04 · NFT claim" title="The crew gets first dibs."/><div className="app-grid"><div className="section-copy" data-reveal><h3>Got an IMD NFT or a Swarm Pepe?</h3><p>Connect the wallet holding your NFTs. The site checks every eligible token directly on Ethereum, then shows exactly what you can claim.</p><ul className="facts"><li>IMD NFT IDs 0–1999 · 100M ADAM total</li><li>Swarm Pepe IDs 1–1178 · 10M ADAM total</li><li>10% available at launch, then daily for 9 more days</li><li>Entitlements follow the NFT, including prior claims</li></ul>{data&&<p>Next unlock: <strong>{nextUnlock(data.launch,data.deadline,now)}</strong><br/>Claim window closes {new Date(data.deadline*1000).toLocaleString()}. Unclaimed tokens can then be burned.</p>}</div>
  <div className="panel claim-panel" data-reveal><div className="card-top"><h3>Your NFT allocation</h3><span className="badge">Ethereum</span></div>{!wallet.account?<div className="empty"><Icon name="spark" size={40}/><h3>A spot for every surf buddy.</h3><p>Connect your wallet to find your eligible NFTs.</p><button type="button" className="primary" onClick={wallet.connect}><Icon name="wallet" size={16}/>Connect wallet</button></div>:<><p>Scan 3,178 eligible IDs via Multicall3. A full scan may take a minute.</p><button type="button" onClick={scan} disabled={scanBusy}>{scanBusy?`Scanning ${scanned.toLocaleString()} / 3,178…`:nfts?'Rescan NFTs':'Find my NFTs'}</button>{scanBusy&&<><progress value={scanned} max={3178} aria-label="NFT scan progress"/><button type="button" onClick={()=>{scanAbort.current?.abort();setScanBusy(false);setScanError('Scan cancelled. Select Find my NFTs to start a complete scan.');}}>Cancel scan</button></>}{scanError&&<p role="alert" className="alert">{scanError} Retry a complete scan.</p>}{nfts?.length===0&&<p>No eligible NFTs found in this wallet. Switch accounts in your wallet and scan again.</p>}{!!nfts?.length&&<><div className="nft-list">{nfts.map(n=><label className="nft-row" key={`${n.collection}:${n.id}`}><input type="checkbox" checked={selected.includes(`${n.collection}:${n.id}`)} disabled={n.claimable===0n||wallet.busy} onChange={e=>setSelected(v=>e.target.checked?[...v,`${n.collection}:${n.id}`]:v.filter(k=>k!==`${n.collection}:${n.id}`))}/><span><strong>{collections[n.collection].name} #{n.id}</strong><small>Share {fmt(n.share)} · claimed {fmt(n.claimed)} ADAM</small><small>Claimable {fmt(n.claimable)} ADAM</small></span></label>)}</div><p><strong>{fmt(selectedDue)} ADAM</strong> selected</p><p className="notice">Claim & Stake resets the 24h lock on your entire staked balance. Batches contain up to 40 NFTs from one collection; each batch needs a separate wallet confirmation.</p><div className="actions"><button type="button" className="primary" disabled={!canWrite||!selectedDue} onClick={()=>claimNfts(false)}>Claim selected</button><button type="button" disabled={!canWrite||!selectedDue} onClick={()=>claimNfts(true)}>Claim & Stake</button></div></>}</>}</div></div></section>
 <section id="stake" className="section stake-section"><Heading n="05 · Stake" title="Same wave. More rewards."/><div className="app-grid stake-grid"><div className="panel" data-reveal><div className="card-top"><h3>Stake ADAM</h3><span className="badge">24h lock</span></div><div className="balance-pair"><Metric label="Wallet balance" value={fmt(personal?.balance)} note="ADAM"/><Metric label="Staked balance" value={fmt(personal?.staked)} note="ADAM"/></div><label htmlFor="stake-amount">ADAM amount</label><div className="amount-field"><input id="stake-amount" inputMode="decimal" autoComplete="off" placeholder="0.00" value={amount} onChange={e=>{setAmount(e.target.value);setActionError('');}} aria-invalid={!!actionError} aria-describedby="amount-help amount-error"/><span>ADAM</span></div><p id="amount-help" className="muted">Approval is for the amount entered. A new stake resets the 24h lock on all your staked ADAM.</p><p id="amount-error" role="alert" className="alert">{actionError}</p><div className="actions"><button type="button" className="primary" disabled={!canWrite||!personal} onClick={()=>stake()}>Approve & Stake</button><button type="button" disabled={!canWrite||!personal||locked||personal.staked===0n} onClick={()=>stake(true)}>Unstake</button><button type="button" disabled={!canWrite||!personal||locked||personal.staked===0n} onClick={()=>wallet.run('Exit stake',send=>send('staking','exit'))}>Exit all</button></div><p className="lock-status">{personal?personal.staked===0n?'No ADAM staked yet.':`Stake lock: ${countdown(personal.unlock,now)}${locked?` · until ${new Date(personal.unlock*1000).toLocaleString()}`:''}`:'Connect your wallet to see your balance and stake lock.'}</p><p className="muted">Exit withdraws all principal and transferable rewards. Claim any IMDSTR ETH budget separately.</p></div>
  <div className="panel" data-reveal><span className="eyebrow">Your earned rewards</span><h3>Three ways to catch a wave.</h3>{rewards.filter(t=>t.key!=='imdstr'||data?.direct).map(t=>{const i=rewards.indexOf(t);return <div className="reward-row" key={t.key}><div><strong>${t.symbol}</strong><span>{fmt(personal?.earned[i],data?.decimals[i]??18)}</span></div><button type="button" disabled={!canWrite||!personal?.earned[i]} onClick={()=>wallet.run(`Claim ${t.symbol}`,send=>send('staking','claimReward',[t.address]))}>Claim {t.symbol}</button></div>;})}<div className="budget"><div className="card-top"><h4>IMDSTR ETH budget</h4><strong>{fmt(personal?.budget)} ETH</strong></div><p className="muted">Your ETH allocation buys IMDSTR when you claim. Quote simulates the actual claim, including pool effects. Limit: {fmt(data?.maxClaim)} ETH per claim.</p><div className="form-pair"><label>ETH budget to spend<input aria-describedby="quote-error" inputMode="decimal" autoComplete="off" placeholder="0.001" value={budget} onChange={e=>setBudget(e.target.value)}/></label><label>Slippage (%)<input aria-describedby="quote-error" inputMode="decimal" autoComplete="off" value={slippage} onChange={e=>setSlippage(e.target.value)}/></label></div><p id="quote-error" role="alert" className="alert">{quoteError}</p>{quote&&<p role="status" className="notice">Quote: {fmt(quote.out,data?.decimals[2]??18)} IMDSTR · minimum {fmt(quote.min,data?.decimals[2]??18)}. {now>=quote.expires?'Quote expired. Refresh it.':`Valid for ${quote.expires-now}s.`}</p>}<div className="actions"><button type="button" onClick={getQuote} disabled={!canWrite||quoteBusy}>{quoteBusy?'Quoting…':'Get quote'}</button><button type="button" disabled={!canWrite||!quote||now>=quote.expires||quote.account!==wallet.account} onClick={()=>{if(quote)void wallet.run('Claim IMDSTR',send=>send('staking','claimIMDSTR',[quote.amount,quote.min,BigInt(now+600)]));}}>Claim IMDSTR</button></div></div><p className="muted">Reward claims remain available during the stake lock. Network gas is paid separately.</p></div></div>{personalError&&<p role="alert" className="alert">Wallet balances unavailable: {personalError} <button type="button" onClick={refresh}>Retry balances</button></p>}</section>
 <section id="keepers" className="section"><Heading n="06 · Keepers" title="Anyone can be a keeper."/><div className="keeper-grid"><div data-reveal><h3>Process fees. Collect 0.5%.</h3><p>Convert available Treasury fees into rewards for the crew. The bounty is 0.5% of newly processed ETH, before the 90/10 split. Gas and price conditions affect whether processing is worthwhile.</p><p>Unsplit: <strong>{fmt(data?.unsplit)} ETH</strong><br/>Cooldown: {data?countdown(data.availableAt,now):'Loading…'}</p></div><div className="panel" data-reveal><div className="actions"><button type="button" className="primary" disabled={!canWrite||!data||data.availableAt>now} onClick={()=>wallet.run('Process Treasury',send=>send('treasury','process'))}>Process fees</button><button type="button" disabled={!canWrite||!personal?.keeper} onClick={()=>wallet.run('Claim keeper bounty',(send,account)=>send('treasury','claimKeeper',[account]))}>Claim keeper bounty</button></div><p>Deferred bounty: <strong>{fmt(personal?.keeper)} ETH</strong></p><p className="muted">Process pays the bounty automatically when possible. Claim keeper bounty withdraws a previously deferred payment. The contract simulation checks cooldown and available work before your wallet opens.</p></div></div></section>
 {wallet.account?.toLowerCase()===addresses.relayer.toLowerCase()&&<Relayer wallet={wallet} now={now}/>}
 <section id="parents" className="section parents-section"><Heading n="07 · Origins" title="Parents of ADAM." lead="A nod to the people behind the inspiration. Profile credits are acknowledgments, with no implied endorsement."/><div className="parents">{[{handle:'surfcoderepeat',name:'Surf. Code. Repeat.',file:'surf'},{handle:'Rhynotic',name:'A little creative chaos.',file:'rhynotic'}].map(p=><article key={p.file} className="panel parent" data-reveal><img className="parent-banner" src={`./images/${p.file}-banner.jpg`} alt={`${p.handle} profile banner`} loading="lazy" width="1500" height="500"/><div className="parent-meta"><img src={`./images/${p.file}.jpg`} alt={`${p.handle} avatar`} loading="lazy" width="64" height="64"/><div><h3>{p.name}</h3><External href={`https://x.com/${p.handle}`}>@{p.handle}</External></div></div></article>)}</div></section>
 </main>
 <footer className="site-footer"><div className="footer-top"><div><a className="footer-brand" href="#home">ADAM</a><p>Good waves. Open contracts. Shared rewards.</p><a className="button ghost" href={links.x} target="_blank" rel="noopener noreferrer"><XLogo size={16}/>Follow @IaMaDamIMD on X<span className="sr-only"> (opens in a new tab)</span></a></div>
  <div className="footer-links"><span className="eyebrow">Links</span><External href={links.dex}>DexScreener</External><External href={links.buy}>Buy on Uniswap</External><External href={links.lp}>LP NFT</External><a href="#about">About ADAM</a></div></div>
  <div className="footer-contracts"><span className="eyebrow">Mainnet contracts</span><ul>{Object.entries(addresses).filter(([n])=>n in contractNames).map(([n,a])=><li key={n}><span className="contract-name">{contractNames[n]}</span><code>{a}</code><span className="contract-tools"><Copy text={a} label={`Copy ${contractNames[n]} address`} compact/><a className="icon-button" href={explorer(a)} target="_blank" rel="noopener noreferrer" aria-label={`${contractNames[n]} on Etherscan (opens in a new tab)`}><Icon name="external" size={16}/></a></span></li>)}</ul></div>
  <p className="footer-note">Ethereum mainnet · chain ID 1 · $ADAM · No backend, no API keys: every number comes from public RPCs and your wallet.</p></footer>
 <div className="wallet-state" aria-live="polite">{wallet.account&&wallet.chain!==1&&<div className="notice">Your wallet is on another network. <button type="button" onClick={wallet.switchChain}>Switch to Ethereum</button></div>}{(wallet.status||wallet.error)&&<div className="tx-panel"><strong>{wallet.status||'Wallet connection'}</strong>{wallet.error&&<p role="alert" className="alert">{wallet.error}</p>}{wallet.hash&&<External href={`https://etherscan.io/tx/${wallet.hash}`}>View transaction</External>}{!wallet.busy&&<button type="button" className="copy" onClick={()=>{wallet.dismiss();}} aria-label="Dismiss transaction status">Dismiss</button>}</div>}</div>
 </>;
}
function Relayer({wallet,now}:{wallet:ReturnType<typeof useWallet>;now:number}){
 const [id,setId]=useState(''),[report,setReport]=useState<ReturnType<typeof mapAttestation>>(),[state,setState]=useState(''),[busy,setBusy]=useState(false),[valid,setValid]=useState(false);
 async function fetchReport(){setBusy(true);setReport(undefined);setValid(false);setState('Fetching attestation…');try{const request=id.trim();if(!/^(?:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|0x[0-9a-fA-F]{64})$/.test(request))throw Error('Paste a UUID or bytes32 request ID.');const response=await fetch(`${links.api}/${encodeURIComponent(request)}/attestation`,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error(`Attestation unavailable (${response.status}). Check the request ID and try again.`);const payload=await response.json();const parsed=mapAttestation(payload);if(request.startsWith('0x')?parsed.a.requestId.toLowerCase()!==request.toLowerCase():String(payload.requestId).toLowerCase()!==request.toLowerCase())throw Error('The API returned a different request ID. Check the request and retry.');setReport(parsed);const sim=await (await getClient()).simulateContract({account:wallet.account,address:addresses.oracle,abi:abis.oracle,functionName:'submit',args:[parsed.a,parsed.signature]});if(sim.result!==true)throw Error('Oracle simulation rejected this report. Check expiry, replay, signer, domain, and whether a newer report is already accepted.');setValid(true);setState('Valid: deployed oracle simulation accepts this report. It will be checked again before submission.');}catch(e){setState(explain(e));}finally{setBusy(false);}}
 return <section id="relayer" className="section"><Heading n="Relayer workspace" title="Bring in the daily report."/><p>Only the configured relayer sees this section. The contract enforces authorization.</p><div className="panel"><label htmlFor="request-id">IMD oracle request ID</label><input id="request-id" disabled={busy} value={id} autoComplete="off" onChange={e=>{setId(e.target.value);setReport(undefined);setValid(false);setState('');}} placeholder="Paste the request UUID"/><div className="actions"><button type="button" disabled={busy||wallet.busy} onClick={fetchReport}>{busy?'Fetching…':'Fetch & validate'}</button><button type="button" className="primary" disabled={!valid||!report||wallet.busy||wallet.chain!==1||now>Number(report.a.expiresAt)||now>Number(report.a.issuedAt)+93600} onClick={()=>{if(report)void wallet.run('Submit oracle report',send=>send('oracle','submit',[report.a,report.signature]));}}>Submit report</button></div><p role="status">{state}</p>{report&&<div className="report-preview"><h3>Rank code {report.code}</h3><p>{rankWeights(report.code).map((w,i)=>`${rewards[i].symbol} ${w/100}%`).join(' / ')}</p><p>Issued {new Date(Number(report.a.issuedAt)*1000).toUTCString()}<br/>Expires {new Date(Number(report.a.expiresAt)*1000).toUTCString()}<br/>Blocks {report.a.fromBlock.toString()}–{report.a.toBlock.toString()} · panel {report.a.agreed}/{report.a.panelSize} · quorum {report.a.quorum}</p><code>{report.a.requestId}</code></div>}<details open><summary>Daily oracle question</summary><p className="question">{QUESTION}</p><Copy text={QUESTION} label="Copy daily question"/></details></div></section>;
}
